[project]
name = "transcript-generation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "yt-dlp>=2025.9.5",
    "openai>=1.40.0",
    "python-dotenv>=1.0.1",
]
